module.exports = {
  UNDEFINED_STATE: new Error('UNDEFINED_STATE'),
  UNDEFINED_CLAUSE: new Error('UNDEFINED_CLAUSE'),
  CLAUSE_NOT_STRING: new Error('CLAUSE_NOT_STRING'),
  STATE_NOT_OBJECT: new Error('STATE_NOT_OBJECT')
}
