module.exports = {
  UNDEFINED_STATE: new Error('UNDEFINED_STATE'),
  UNDEFINED_CLAUSE: new Error('UNDEFINED_CLAUSE'),
  UNDEFINED_SELECTOR: new Error('UNDEFINED_SELECTOR'),
  CLAUSE_NOT_STRING: new Error('CLAUSE_NOT_STRING'),
  STATE_NOT_OBJECT: new Error('STATE_NOT_OBJECT'),
  SELECTOR_NOT_STRING: new Error('SELECTOR_NOT_STRING'),
  INVALID_SELECTOR: new Error('INVALID_SELECTOR')
}
